# Generated by Django 3.1.5 on 2021-04-19 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concent', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodHabitsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose_your_dietary_habit', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('I eat only vegetables. I DO NOT eat milk, eggs, chiken, mutton or fish. (Vegan)', 'I eat only vegetables. I DO NOT eat milk, eggs, chiken, mutton or fish. (Vegan)'), ('I eat only milk and vegetables. I DO NOT eat eggs, chicken, mutton, fish. (Lacto-Vegetarian)', 'I eat only milk and vegetables. I DO NOT eat eggs, chicken, mutton, fish. (Lacto-Vegetarian)'), ('I eat only eggs and vegetables. I DO NOT eat milk, chicken, mutton or fish. (Eggetarian)', 'I eat only eggs and vegetables. I DO NOT eat milk, chicken, mutton or fish. (Eggetarian)'), ('I eat milk, eggs and vegetables. I DO NOT eat chicken, mutton, fish.(Lacto-ova-vegetarian)', 'I eat milk, eggs and vegetables. I DO NOT eat chicken, mutton, fish.(Lacto-ova-vegetarian)'), ('I eat vegetables, milk, egg, chicken, mutton, fish. (Non-vegetarian)', 'I eat vegetables, milk, egg, chicken, mutton, fish. (Non-vegetarian)'), ('I eat vegetables, milk and fish. I DO NOT eat eggs, chicken and mutton. (Pescatarian)', 'I eat vegetables, milk and fish. I DO NOT eat eggs, chicken and mutton. (Pescatarian)')], max_length=100)),
                ('Choose_meals_consumed_in_a_day', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Mid-morning snack', 'Mid-morning snack'), ('Lunch', 'Lunch'), ('Afternoon snack', 'Afternoon snack'), ('Evening snack', 'Evening snack'), ('Dinner', 'Dinner'), ('Bed-time snack', 'Bed-time snack'), ('Other', 'Other')], max_length=91)),
                ('other_meal', models.CharField(blank=True, max_length=1000)),
                ('breakfast', models.CharField(blank=True, max_length=1000)),
                ('lunch', models.CharField(blank=True, max_length=1000)),
                ('dinner', models.CharField(blank=True, max_length=1000)),
                ('snack', models.CharField(blank=True, max_length=1000)),
                ('canteen', models.CharField(blank=True, max_length=1000)),
                ('tiffin', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('I carry my tiffin daily', 'I carry my tiffin daily'), ('I carry my tiffin only once a week', 'I carry my tiffin only once a week'), ('I carry my tiffin 2-3 times a week', 'I carry my tiffin 2-3 times a week'), ('I carry my tiffin more than 3 times a week', 'I carry my tiffin more than 3 times a week'), ('I never carry my tiffin', 'I never carry my tiffin')], max_length=100)),
                ('midday_meal', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('Yes, I get it and I love it', 'Yes, I get it and I love it'), ('Yes, I get it but I dont Like it so I eat something else', 'Yes, I get it but I dont Like it so I eat something else'), ('No, I dont get Mid-day meal in my school', 'No, I dont get Mid-day meal in my school')], max_length=100)),
                ('soyabean', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('Daily', 'Daily'), ('Thrice in a week', 'Thrice in a week'), ('Once in a week', 'Once in a week'), ('Twice in a month', 'Twice in a month'), ('Monthly', 'Monthly'), ('Never', 'Never')], max_length=100)),
                ('bananapeel', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=100)),
                ('bottlegourd', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NutriAnthropometricParametersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_your_weight', models.CharField(blank=True, max_length=100)),
                ('Enter_your_height', models.CharField(blank=True, max_length=100)),
                ('Enter_your_waist_circumference', models.CharField(blank=True, max_length=100)),
                ('Enter_your_hip_circumference', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NutriInfotainmentSurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_volunteer', models.CharField(blank=True, max_length=255)),
                ('name_of_student', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('birthdate', models.DateField(max_length=20, null=True)),
                ('residential_address', models.CharField(max_length=2000, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('name_of_school', models.CharField(blank=True, max_length=255)),
                ('address_of_school', models.CharField(blank=True, max_length=255)),
                ('pincode_of_school', models.CharField(blank=True, max_length=10)),
                ('personal_contact_number', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, choices=[('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Sikhism', 'Sikhism'), ('Jainism', 'Jainism'), ('Buddhism', 'Buddhism'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NutriSocioDemographicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_live_with', models.CharField(blank=True, choices=[('My parents', 'My parents'), ('My parents and siblings', 'My parents and siblings'), ('My parents, siblings and grandparents', 'My parents, siblings and grandparents'), ('My parents, siblings, grandparents, aunts, uncles and cousins', 'My parents, siblings, grandparents, aunts, uncles and cousins'), ('Others', 'Others')], max_length=100)),
                ('number_of_family_members', models.CharField(blank=True, max_length=100)),
                ('name_of_the_guardian', models.CharField(blank=True, max_length=100)),
                ('age_of_the_guardian', models.CharField(blank=True, max_length=100)),
                ('education_of_the_guardian', models.CharField(blank=True, choices=[('Professional degree (Post graduate)', 'Professional degree (Post graduate)'), ('Graduate (Bachelors)', 'Graduate (Bachelors)'), ('Higher Secondary certificate (12th Std)', 'Higher Secondary certificate (12th Std)'), ('Secondary school certificate (SSC - 10th Std)', 'Secondary school certificate (SSC - 10th Std)'), ('Middle school (5th to 10th std)', 'Middle school (5th to 10th std)'), ('Primary school (1st to 4th std)', 'Primary school (1st to 4th std)'), ('Illiterate (No education)', 'Illiterate (No education)'), ('Other', 'Other')], max_length=100)),
                ('occupation_of_the_guardian', models.CharField(blank=True, choices=[('Accountants', 'Accountants'), ('Administrative Assistants', 'Administrative Assistants'), ('Advocates', 'Advocates'), ('Anganwadi Worker', 'Anganwadi Worker'), ('Architects', 'Architects'), ('Assemblers', 'Assemblers'), ('Auditors', 'Auditors'), ('Business Person', 'Business Person'), ('Cleaners (Washing Windows And Other Glass Surfaces Of Buildings)', 'Cleaners (Washing Windows And Other Glass Surfaces Of Buildings)'), ('College Principals', 'College Principals'), ('Commercial Truck Drivers', 'Commercial Truck Drivers'), ('Cooks', 'Cooks'), ('Craftsmen', 'Craftsmen'), ('Crane Operators', 'Crane Operators'), ('Doctors', 'Doctors'), ('Engineers', 'Engineers'), ('Expert Musicians', 'Expert Musicians'), ('Farmers', 'Farmers'), ('Fishermen', 'Fishermen'), ('Garbage Collector', 'Garbage Collector'), ('General Office Clerks', 'General Office Clerks'), ('Housekeeper/ Housemaid (Hotels/ House)', 'Housekeeper/ Housemaid (Hotels/ House)'), ('Lecturers', 'Lecturers'), ('Mechanist', 'Mechanist'), ('Newspaper Editors', 'Newspaper Editors'), ('Nurse', 'Nurse'), ('Office Assistants', 'Office Assistants'), ('Paramedics', 'Paramedics'), ('Plant And Machine Operators', 'Plant And Machine Operators'), ('Plumbers', 'Plumbers'), ('Police Officers', 'Police Officers'), ('Reading And Emptying Meters', 'Reading And Emptying Meters'), ('Receptionists', 'Receptionists'), ('Retired', 'Retired'), ('Salesman', 'Salesman'), ('Scientists', 'Scientists'), ('Security Guard (Housing Societies/Company/Banks/Land)', 'Security Guard (Housing Societies/Company/Banks/Land)'), ('Senior Administrative Officers', 'Senior Administrative Officers'), ('Software Development', 'Software Development'), ('Soldiers', 'Soldiers'), ('Stocking Vending Machines', 'Stocking Vending Machines'), ('Street Vendor', 'Street Vendor'), ('Sweeper', 'Sweeper'), ('Unemployed', 'Unemployed'), ('OTHERS', 'OTHERS')], max_length=300)),
                ('monthly_family_income', models.CharField(blank=True, choices=[('>199,862', '>199,862'), ('99,931- 199,861', '99,931- 199,861'), ('74,755 - 99,930', '74,755 - 99,930'), ('49,962- 74,755', '49,962- 74,755'), ('29,973- 49,961', '29,973- 49,961'), ('10,002- 29,972', '10,002- 29,972'), ('< 10,001', '< 10,001')], max_length=100)),
                ('ration_card_color_is', models.CharField(blank=True, choices=[('Red color', 'Red color'), ('Orange color', 'Orange color'), ('White color', 'White color'), ('No ration card', 'No ration card')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('nutrileader', models.CharField(choices=[('Nutri-Leader', 'Nutri-Leader'), ('School-Student', 'School-Student')], default=False, max_length=20)),
                ('contact', models.CharField(blank=True, max_length=25500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMChildParentsRegister',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('personalcontact', models.CharField(max_length=200)),
                ('ICDSname', models.CharField(max_length=200)),
                ('childis', models.CharField(choices=[('SAM', 'SAM'), ('MAM', 'MAM')], max_length=50, null=True)),
                ('childfirstname', models.CharField(max_length=200, null=True)),
                ('childlastname', models.CharField(max_length=200, null=True)),
                ('childbirthdate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMChild',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.CharField(max_length=255)),
                ('personalcontact', models.CharField(max_length=200)),
                ('ICDSname', models.CharField(max_length=200)),
                ('ICDScenteraddress', models.CharField(max_length=200)),
                ('ICDScentercontact', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('weightunit', models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], max_length=255)),
                ('height', models.IntegerField()),
                ('heightunit', models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50)),
                ('bmi', models.DecimalField(decimal_places=3, max_digits=10)),
                ('waist', models.IntegerField(null=True)),
                ('waistunit', models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20)),
                ('hip', models.IntegerField(null=True)),
                ('hipunit', models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20)),
                ('whratio', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('whratioderived', models.IntegerField(null=True)),
                ('foodhabits', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=20, null=True)),
                ('uploaded_photo', models.FileField(upload_to='smchilddocuments/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolStudentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=False, max_length=255)),
                ('birthdate', models.CharField(max_length=2000, null=True)),
                ('age', models.CharField(blank=True, max_length=200)),
                ('schooladdress', models.CharField(max_length=2000, null=True)),
                ('schoolcontact', models.CharField(blank=True, max_length=25500)),
                ('education', models.CharField(blank=True, choices=[('Professionaldegree', 'Professionaldegree'), ('Graduate', 'Graduate (Bachelors)'), ('Middleschool', 'Middle school (5th to 10th std)'), ('Primaryschool', 'Primary school (1st to 4th std)'), ('Illiterate', 'Illiterate (No education)')], max_length=2000)),
                ('occupation', models.CharField(blank=True, choices=[('Legislators,Senior Officials & Managers', 'Legislators,Senior Officials & Managers'), ('Professionals', 'Professionals'), ('Technicians and Associate Professionals', 'Technicians and Associate Professionals'), ('Clerks', 'Clerks'), ('Skilled workers and Shop & Market sales workers ', 'Skilled workers and Shop & Market sales workers '), ('Skilled Agricultural', 'Skilled Agricultural and Fishery workers'), ('Craft and Related Trade Workers', 'Craft and Related Trade Workers'), ('Plant and Machine Operators and Assemblers', 'Plant and Machine Operators and Assemblers'), ('Elementary Occupation', 'Elementary Occupation'), ('Security guard', 'Security guard'), ('Housekeeper or Housemaid', 'Housekeeper or Housemaid'), ('Nurse', 'Nurse'), ('Anganwadi Worker', 'Anganwadi Worker'), ('Retired', 'Retired'), ('Others', 'Others')], max_length=2000)),
                ('annualincome', models.CharField(blank=True, choices=[('199,862', '199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('10,001', '10,001')], max_length=25500)),
                ('schoolcoordinatorincharge', models.CharField(blank=True, max_length=25500)),
                ('foodhabits', models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=25500)),
                ('profile_photo', models.ImageField(blank=True, upload_to='SchoolStudentParent/%Y/%m/%d')),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('schoolname', models.CharField(max_length=200)),
                ('personaladdress', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCoordinator',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=25500)),
                ('schoolname', models.CharField(max_length=2000)),
                ('schoolcontact', models.CharField(blank=True, max_length=25500)),
                ('position', models.CharField(choices=[('teaching-staff', 'Teaching Staff'), ('non-teaching-staff', 'Non-Teaching Staff'), ('principal', 'Principal')], max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutriGardenExpert',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MukhyaSevika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=False, max_length=255)),
                ('ICDSname', models.CharField(max_length=2000, null=True)),
                ('ICDScenteraddress', models.CharField(max_length=2000, null=True)),
                ('ICDScontact', models.CharField(max_length=2000, null=True)),
                ('contact', models.CharField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnganwadiWorkersRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=False, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=25500)),
                ('ICDSname', models.CharField(max_length=2000, null=True)),
                ('ICDScenteraddress', models.CharField(max_length=2000, null=True)),
                ('ICDScontact', models.CharField(max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnemicPregnantWoman',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('personalcontact', models.CharField(max_length=200)),
                ('ICDSname', models.CharField(max_length=200)),
                ('trimester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnemicLactatingMother',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('personalcontact', models.CharField(max_length=200)),
                ('childbirthdate', models.DateField(blank=True, null=True)),
                ('ICDSname', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='anemicadolescentgirl',
            fields=[
                ('uid', models.CharField(default=False, max_length=255, primary_key=True, serialize=False)),
                ('personalcontact', models.CharField(max_length=200)),
                ('ICDSname', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
